apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-t1mv
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:mdsaud-tenant-devfile-sample-t1mv
        name: container-image
        resources: {}
status: {}
